import React from 'react';
import Navbar from '@/components/Navbar';
import { Link } from 'react-router-dom';

const TermsPage = () => {
    return (
        <div className="min-h-screen bg-[#0a0a0a] text-white">
            <Navbar />
            <div className="max-w-4xl mx-auto px-6 py-16">
                <h1 className="text-4xl font-bold mb-2" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
                    Terms &amp; <span className="bg-gradient-to-r from-emerald-400 to-lime-400 bg-clip-text text-transparent">Conditions</span>
                </h1>
                <p className="text-gray-500 mb-10 text-sm">Last updated: February 21, 2026</p>

                <div className="space-y-10 text-gray-300 leading-relaxed" style={{ fontFamily: 'Inter, sans-serif' }}>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing or using <strong className="text-emerald-400">Botfolio</strong> ("Service"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our Service. These terms apply to all users, visitors, and others who access or use the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
                        <p>Botfolio is an AI-powered portfolio chatbot platform that allows users to create, host, and share intelligent portfolio chatbots trained on their professional data (resume, skills, experience). The Service includes a web application, AI chatbot generation, file storage, and analytics features.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">3. Account Registration</h2>
                        <p className="mb-2">To use certain features of the Service, you must create an account. You agree to:</p>
                        <ul className="list-disc list-inside space-y-1 ml-2">
                            <li>Provide accurate and complete registration information</li>
                            <li>Maintain the security of your account credentials</li>
                            <li>Notify us immediately of any unauthorized use of your account</li>
                            <li>Accept responsibility for all activities that occur under your account</li>
                            <li>Be at least 13 years of age to create an account</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
                        <p className="mb-2">You agree not to use the Service to:</p>
                        <ul className="list-disc list-inside space-y-1 ml-2">
                            <li>Upload content that is illegal, harmful, threatening, or defamatory</li>
                            <li>Impersonate any person or entity</li>
                            <li>Upload content containing viruses or malicious code</li>
                            <li>Scrape, crawl, or otherwise extract data from the platform without permission</li>
                            <li>Use the Service in a way that could damage or overburden our infrastructure</li>
                            <li>Attempt to gain unauthorized access to any part of the Service</li>
                            <li>Use the Service for any unlawful purpose or in violation of any regulations</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. Content and Intellectual Property</h2>
                        <p className="mb-2"><strong className="text-white">Your Content:</strong> You retain ownership of the content you upload to Botfolio (resumes, portfolio files, etc.). By uploading content, you grant us a limited, non-exclusive license to process, store, and use your content solely to provide the Service.</p>
                        <p className="mt-3"><strong className="text-white">Our Content:</strong> The Botfolio platform, its design, code, branding, and features are owned by us and protected by intellectual property laws. You may not copy, modify, or distribute any part of our platform without written permission.</p>
                        <p className="mt-3"><strong className="text-white">AI-Generated Content:</strong> Content generated by the AI chatbot is based on your uploaded materials. You are responsible for ensuring your uploaded content does not violate any third-party rights.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">6. Subscription Plans and Payments</h2>
                        <p className="mb-2">Botfolio offers Free, Starter, and Pro subscription tiers. By subscribing to a paid plan:</p>
                        <ul className="list-disc list-inside space-y-1 ml-2">
                            <li>You authorize us to charge your payment method on a recurring basis</li>
                            <li>Payments are processed securely through Razorpay</li>
                            <li>Subscription fees are non-refundable except as required by law</li>
                            <li>We reserve the right to change pricing with 30 days' notice</li>
                            <li>Downgrading your plan may result in reduced functionality</li>
                        </ul>
                        <p className="mt-3"><strong className="text-white">Free Tier Limitations:</strong> The free tier is limited to 1 portfolio and 5 AI chatbot requests per day. We reserve the right to modify these limits at any time.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">7. Privacy</h2>
                        <p>Your use of the Service is also governed by our <Link to="/privacy" className="text-emerald-400 hover:underline">Privacy Policy</Link>, which is incorporated into these Terms by reference. Please review our Privacy Policy carefully before using the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">8. Disclaimer of Warranties</h2>
                        <p>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of viruses. We disclaim all warranties including merchantability, fitness for a particular purpose, and non-infringement.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
                        <p>To the maximum extent permitted by law, Botfolio shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability to you for any cause of action shall not exceed the amounts paid by you to us in the 12 months preceding the claim.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">10. Termination</h2>
                        <p>We reserve the right to suspend or terminate your account at any time for violation of these Terms. You may delete your account at any time through the Settings page. Upon termination, your right to use the Service will immediately cease, and your data may be deleted after a reasonable grace period.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">11. Changes to Terms</h2>
                        <p>We may modify these Terms from time to time. We will notify you of material changes via email or by posting a notice on our website. Your continued use of the Service after the effective date of revised Terms constitutes acceptance of the changes.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">12. Governing Law</h2>
                        <p>These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in India.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">13. Contact Us</h2>
                        <p>If you have questions about these Terms, please contact us:</p>
                        <ul className="list-none space-y-1 mt-2 ml-2">
                            <li>📧 Email: <a href="mailto:legal@botfolio.app" className="text-emerald-400 hover:underline">legal@botfolio.app</a></li>
                            <li>🌐 Website: <Link to="/contact" className="text-emerald-400 hover:underline">Contact Form</Link></li>
                        </ul>
                    </section>
                </div>
            </div>

            <footer className="border-t border-emerald-500/20 py-6 mt-12">
                <div className="max-w-7xl mx-auto px-6 text-center text-gray-500 text-sm">
                    <p>© {new Date().getFullYear()} Botfolio. All rights reserved. &nbsp;|&nbsp;
                        <Link to="/privacy" className="hover:text-emerald-400 mx-2">Privacy</Link>
                        <Link to="/terms" className="hover:text-emerald-400 mx-2">Terms</Link>
                        <Link to="/contact" className="hover:text-emerald-400 mx-2">Contact</Link>
                    </p>
                </div>
            </footer>
        </div>
    );
};

export default TermsPage;
